### ISSUE TITLE
Clear disk space on servers

### ISSUE THREAD

**Issue by alykat** [nprapps/elections22#34]

**Comment by jsfenfen** [comment]
Cleared out space on the following servers:

- primaries  
- elections-staging  
- liveblog  
- covid 

This was caused by the accumulation of linux header files, see more here: https://kaiwern.com/posts/2020/03/16/aws-ec2-disk-space-full/ . Some futzing may be required when there's no room whatsoever but once there's a little `sudo apt autoremove` seems to free up ~2GB of disk space.
