### ISSUE TITLE
Make sure we have the latest Cook ratings before Election Day

### ISSUE THREAD

**Issue by alykat** [nprapps/elections22#48]

**Comment by jsfenfen** [comment]
Looks like they go all the way to the wire, here's 2018. (election day was Nov. 6, their last update was Nov. 5). 

<img width="482" alt="image" src="https://user-images.githubusercontent.com/639012/196303071-b8b330ec-1eba-448b-a59c-74b67116c24f.png">

**Comment by jsfenfen** [comment]
Since 10/24 Cook has changed the ratings for *20* house races and 1 senate race. 

10/24 - https://www.cookpolitical.com/analysis/house/new-york-house/ny-17-rating-change-dccc-chair-maloney-moves-lean-democrat-toss 

NY-17 Lean D to Toss Up

10/25 - https://www.cookpolitical.com/analysis/house/house-overview/house-overview-10-rating-changes-democrats-blue-state-problems-grow 

RATING CHANGES:
AK-AL: Toss Up to Lean D
CA-49: Lean D to Toss Up
CT-05: Lean D to Toss Up
IA-02: Likely R to Lean R
KS-03: Toss Up to Lean D
NY-17: Lean D to Toss Up  [ really part of prior update ]
NC-01: Lean D to Likely D
VA-07: Lean D to Toss Up
VA-10: Solid D to Likely D
WI-03: Lean R to Likely R


10/27 - https://www.cookpolitical.com/analysis/senate/arizona-senate/arizona-senate-shifts-back-toss

AZ senate moves from Lean D to Toss Up

https://www.cookpolitical.com/analysis/house/house-overview/house-rating-changes-10-more-blue-districts-move-gops-direction?check_logged_in=1

11/1

RATING CHANGES:
CA-09: Likely D to Lean D
CA-26: Solid D to Lean D
CA-47: Lean D to Toss Up
IL-06: Likely D to Lean D
IL-14: Likely D to Lean D
NJ-03: Likely D to Lean D
NY-03: Lean D to Toss Up
NY-04: Lean D to Toss Up
NY-25: Solid D to Likely D
OR-05: Toss Up to Lean R

**Comment by jsfenfen** [comment]
This is updated thru today, 11/3...
