### ISSUE TITLE
With an override roster, no "other" rollup is displayed

### ISSUE THREAD

**Issue by alykat** [nprapps/elections22#92]
Example using test data for the OR gov race. There's still 3.9% unaccounted for that should reflect votes for other candidates.

<img width="840" alt="image" src="https://user-images.githubusercontent.com/491318/198719660-4262355a-0bc5-45e6-a9ec-b8dec988dd45.png">

**Comment by jsfenfen** [comment]
This is fixed in an ugly way; the original code envisions a roster *or* a rollup, but not both. The above just lists the top three candidates in the race with a one-off. 

<img width="751" alt="image" src="https://user-images.githubusercontent.com/639012/199351981-47a0c338-5ebb-45ad-89f8-aedc3d637f15.png">

**Comment by jsfenfen** [comment]
eh, this is cleaned up a bit
